// Multilingual strings for FR/EN support
export const strings = {
  en: {
    // App name
    neobank: 'Rwanda\'s First Mobile Neobank',
    
    // Common
    ok: 'OK',
    cancel: 'Cancel',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    retry: 'Retry',
    back: 'Back',
    next: 'Next',
    skip: 'Skip',
    done: 'Done',
    optional: 'Optional',
    required: 'Required',
    
    // Onboarding
    getStarted: 'Get Started',
    feature1: '100% Mobile Banking',
    feature2: 'Instant Transactions',
    feature3: 'Secure & Regulated',
    disclaimer: 'By continuing, you agree to our Terms of Service and Privacy Policy. Licensed by BNR.',
    
    // Authentication
    signIn: 'Sign In',
    signUp: 'Sign Up',
    signOut: 'Sign Out',
    signOutConfirmation: 'Are you sure you want to sign out?',
    
    // KYC
    kyc: 'Identity Verification',
    captureID: 'Capture ID Document',
    captureIDDescription: 'Take a clear photo of your Rwandan National ID card. Ensure all text is visible and readable.',
    captureSelfie: 'Take a Selfie',
    captureSelfieDescription: 'Take a selfie to verify your identity. Look directly at the camera and ensure good lighting.',
    processing: 'Processing...',
    processingKYC: 'Verifying your identity. This may take a few moments.',
    kycCompleted: 'Verification Complete',
    kycCompletedMessage: 'Your identity has been successfully verified. Welcome to Centrika!',
    kycFailed: 'Verification Failed',
    kycFailedMessage: 'We couldn\'t verify your identity. Please try again or contact support.',
    takePhoto: 'Take Photo',
    retake: 'Retake',
    cameraError: 'Camera error occurred',
    permissionRequired: 'Permission Required',
    cameraPermissionMessage: 'Camera access is required for identity verification.',
    grantPermission: 'Grant Permission',
    settings: 'Settings',
    
    // Navigation
    dashboard: 'Dashboard',
    payments: 'Payments',
    qrPay: 'QR Pay',
    cards: 'Cards',
    
    // Dashboard
    hello: 'Hello',
    totalBalance: 'Total Balance',
    availableBalance: 'Available Balance',
    quickActions: 'Quick Actions',
    recentTransactions: 'Recent Transactions',
    noTransactions: 'No transactions yet',
    seeAll: 'See All',
    deposit: 'Deposit',
    transfer: 'Transfer',
    
    // MoMo
    momoDeposit: 'Mobile Money Deposit',
    momoDepositDescription: 'Add money to your Centrika account using Mobile Money (MTN, Airtel)',
    amount: 'Amount',
    phoneNumber: 'Phone Number',
    momoPhoneHint: 'Enter your Mobile Money number',
    dailyLimit: 'Daily Limit',
    fees: 'Fees',
    total: 'Total',
    secureTransaction: 'Secure & encrypted transaction',
    fillAllFields: 'Please fill all required fields',
    invalidAmount: 'Please enter a valid amount (1 - 1,000,000 RWF)',
    invalidPhoneNumber: 'Please enter a valid phone number',
    depositSuccess: 'Deposit initiated successfully! You will receive an SMS confirmation.',
    depositFailed: 'Deposit failed. Please try again.',
    
    // P2P Transfer
    p2pTransfer: 'Send Money',
    p2pTransferDescription: 'Send money instantly to any Centrika user',
    recipient: 'Recipient',
    recipientHint: 'Enter recipient\'s phone number',
    note: 'Note',
    notePlaceholder: 'What\'s this for?',
    characters: 'characters',
    sendMoney: 'Send Money',
    instantTransfer: 'Instant transfer',
    confirmTransfer: 'Confirm Transfer',
    transferConfirmation: 'Please confirm your transfer details:',
    transferSuccess: 'Money sent successfully!',
    transferFailed: 'Transfer failed. Please try again.',
    
    // QR Payment
    qrPayment: 'QR Payment',
    scanQRInstruction: 'Point your camera at the QR code to pay',
    qrPaymentInstruction: 'Scan merchant QR codes to pay instantly and securely',
    confirmPayment: 'Confirm Payment',
    merchant: 'Merchant',
    description: 'Description',
    pay: 'Pay',
    paymentSuccess: 'Payment successful!',
    paymentFailed: 'Payment failed. Please try again.',
    invalidQRCode: 'Invalid QR code. Please try again.',
    qrScanError: 'Error scanning QR code',
    requestingPermission: 'Requesting camera permission...',
    noCameraPermission: 'No camera permission granted',
    scanAgain: 'Scan Again',
    
    // Settings
    account: 'Account',
    profile: 'Profile',
    profileSubtitle: 'Personal information and documents',
    cardsSubtitle: 'Manage your cards',
    security: 'Security',
    securitySubtitle: 'Password and security settings',
    preferences: 'Preferences',
    notifications: 'Notifications',
    notificationsSubtitle: 'Push notifications and alerts',
    biometrics: 'Biometrics',
    biometricsSubtitle: 'Fingerprint and face unlock',
    language: 'Language',
    support: 'Support',
    help: 'Help & Support',
    helpSubtitle: 'Get help and contact support',
    terms: 'Terms of Service',
    termsSubtitle: 'Legal terms and conditions',
    privacy: 'Privacy Policy',
    privacySubtitle: 'How we protect your data',
    about: 'About',
    aboutSubtitle: 'App version and information',
    version: 'Version',
    verified: 'Verified',
  },
  
  fr: {
    // App name
    neobank: 'Première Néobanque Mobile du Rwanda',
    
    // Common
    ok: 'OK',
    cancel: 'Annuler',
    confirm: 'Confirmer',
    yes: 'Oui',
    no: 'Non',
    save: 'Enregistrer',
    edit: 'Modifier',
    delete: 'Supprimer',
    loading: 'Chargement...',
    error: 'Erreur',
    success: 'Succès',
    retry: 'Réessayer',
    back: 'Retour',
    next: 'Suivant',
    skip: 'Ignorer',
    done: 'Terminé',
    optional: 'Facultatif',
    required: 'Obligatoire',
    
    // Onboarding
    getStarted: 'Commencer',
    feature1: 'Banque 100% Mobile',
    feature2: 'Transactions Instantanées',
    feature3: 'Sécurisé et Réglementé',
    disclaimer: 'En continuant, vous acceptez nos Conditions d\'Utilisation et Politique de Confidentialité. Agréé par la BNR.',
    
    // Authentication
    signIn: 'Se Connecter',
    signUp: 'S\'Inscrire',
    signOut: 'Se Déconnecter',
    signOutConfirmation: 'Êtes-vous sûr de vouloir vous déconnecter?',
    
    // KYC
    kyc: 'Vérification d\'Identité',
    captureID: 'Capturer la Pièce d\'Identité',
    captureIDDescription: 'Prenez une photo claire de votre carte d\'identité nationale rwandaise. Assurez-vous que tout le texte est visible et lisible.',
    captureSelfie: 'Prendre un Selfie',
    captureSelfieDescription: 'Prenez un selfie pour vérifier votre identité. Regardez directement la caméra et assurez-vous d\'avoir un bon éclairage.',
    processing: 'Traitement...',
    processingKYC: 'Vérification de votre identité. Cela peut prendre quelques instants.',
    kycCompleted: 'Vérification Terminée',
    kycCompletedMessage: 'Votre identité a été vérifiée avec succès. Bienvenue chez Centrika!',
    kycFailed: 'Vérification Échouée',
    kycFailedMessage: 'Nous n\'avons pas pu vérifier votre identité. Veuillez réessayer ou contacter le support.',
    takePhoto: 'Prendre une Photo',
    retake: 'Reprendre',
    cameraError: 'Erreur de caméra',
    permissionRequired: 'Permission Requise',
    cameraPermissionMessage: 'L\'accès à la caméra est requis pour la vérification d\'identité.',
    grantPermission: 'Accorder la Permission',
    settings: 'Paramètres',
    
    // Navigation
    dashboard: 'Tableau de Bord',
    payments: 'Paiements',
    qrPay: 'Paiement QR',
    cards: 'Cartes',
    
    // Dashboard
    hello: 'Bonjour',
    totalBalance: 'Solde Total',
    availableBalance: 'Solde Disponible',
    quickActions: 'Actions Rapides',
    recentTransactions: 'Transactions Récentes',
    noTransactions: 'Aucune transaction pour le moment',
    seeAll: 'Voir Tout',
    deposit: 'Dépôt',
    transfer: 'Transfert',
    
    // MoMo
    momoDeposit: 'Dépôt Mobile Money',
    momoDepositDescription: 'Ajoutez de l\'argent à votre compte Centrika en utilisant Mobile Money (MTN, Airtel)',
    amount: 'Montant',
    phoneNumber: 'Numéro de Téléphone',
    momoPhoneHint: 'Entrez votre numéro Mobile Money',
    dailyLimit: 'Limite Quotidienne',
    fees: 'Frais',
    total: 'Total',
    secureTransaction: 'Transaction sécurisée et cryptée',
    fillAllFields: 'Veuillez remplir tous les champs requis',
    invalidAmount: 'Veuillez entrer un montant valide (1 - 1,000,000 RWF)',
    invalidPhoneNumber: 'Veuillez entrer un numéro de téléphone valide',
    depositSuccess: 'Dépôt initié avec succès! Vous recevrez une confirmation par SMS.',
    depositFailed: 'Échec du dépôt. Veuillez réessayer.',
    
    // P2P Transfer
    p2pTransfer: 'Envoyer de l\'Argent',
    p2pTransferDescription: 'Envoyez de l\'argent instantanément à tout utilisateur Centrika',
    recipient: 'Destinataire',
    recipientHint: 'Entrez le numéro de téléphone du destinataire',
    note: 'Note',
    notePlaceholder: 'À quoi cela sert-il?',
    characters: 'caractères',
    sendMoney: 'Envoyer de l\'Argent',
    instantTransfer: 'Transfert instantané',
    confirmTransfer: 'Confirmer le Transfert',
    transferConfirmation: 'Veuillez confirmer les détails de votre transfert:',
    transferSuccess: 'Argent envoyé avec succès!',
    transferFailed: 'Échec du transfert. Veuillez réessayer.',
    
    // QR Payment
    qrPayment: 'Paiement QR',
    scanQRInstruction: 'Pointez votre caméra vers le code QR pour payer',
    qrPaymentInstruction: 'Scannez les codes QR des commerçants pour payer instantanément et en toute sécurité',
    confirmPayment: 'Confirmer le Paiement',
    merchant: 'Commerçant',
    description: 'Description',
    pay: 'Payer',
    paymentSuccess: 'Paiement réussi!',
    paymentFailed: 'Échec du paiement. Veuillez réessayer.',
    invalidQRCode: 'Code QR invalide. Veuillez réessayer.',
    qrScanError: 'Erreur lors du scan du code QR',
    requestingPermission: 'Demande de permission caméra...',
    noCameraPermission: 'Aucune permission caméra accordée',
    scanAgain: 'Scanner à Nouveau',
    
    // Settings
    account: 'Compte',
    profile: 'Profil',
    profileSubtitle: 'Informations personnelles et documents',
    cardsSubtitle: 'Gérer vos cartes',
    security: 'Sécurité',
    securitySubtitle: 'Mot de passe et paramètres de sécurité',
    preferences: 'Préférences',
    notifications: 'Notifications',
    notificationsSubtitle: 'Notifications push et alertes',
    biometrics: 'Biométrie',
    biometricsSubtitle: 'Déverrouillage par empreinte et visage',
    language: 'Langue',
    support: 'Support',
    help: 'Aide et Support',
    helpSubtitle: 'Obtenir de l\'aide et contacter le support',
    terms: 'Conditions d\'Utilisation',
    termsSubtitle: 'Termes et conditions légales',
    privacy: 'Politique de Confidentialité',
    privacySubtitle: 'Comment nous protégeons vos données',
    about: 'À Propos',
    aboutSubtitle: 'Version de l\'app et informations',
    version: 'Version',
    verified: 'Vérifié',
  },
};

export default strings;
